--- #YAML:1.0
name:               Sys-Hwloc
version:            0.06
abstract:           Perl wrapper around the hwloc API
author:
    - Bernd Kallies <kallies@zib.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::Constant:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0.89
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
